### ISSUE TITLE
move the constants from ffi

### ISSUE THREAD

**Issue by nskinkel** [dwtj/tweetnaclrs#14]
I don't think it makes sense to have the constants, such as `crypto_sign_BYTES` in `ffi`. I think it makes more sense to put them in the same module where the wrappers are actually defined. For instance, `crypto_sign_BYTES` would go in `crypto_sign.rs`. That way, users of the library won't have to import our internal ffi in order to allocate the correct amount of space for things and can access the constants needed in a more clear/nice way.

**Comment by dwtj** [comment]
:+1:

**Comment by nskinkel** [comment]
Closed in #21
