### ISSUE TITLE
get doctest working and improve bad examples

### ISSUE THREAD

**Issue by nskinkel** [dwtj/tweetnaclrs#15]
`doctest` is currently not running, and I have no idea why. We should fix that and improve some of the (currently mostly bad, unhelpful, and probably slightly wrong) examples.

**Comment by dwtj** [comment]
I've only looked at this briefly, but I think that you can run the tests file-by-file with `rustdoc --test FILE`. I think that most of the examples which we have so far will fail because they lack needed imports and/or identifiers are not defined.

**Comment by dwtj** [comment]
I think I saw a proposal for a _prelude_ feature for `rustdoc` examples, which would make it much easier. I'm not sure what happened with that proposal, though.

**Comment by nskinkel** [comment]
Closed in #22
