### ISSUE TITLE
Move Repo Ownership to @nskinkel

### ISSUE THREAD

**Issue by dwtj** [dwtj/tweetnaclrs#30]
I'm about to transfer ownership of the repo to @nskinkel. Two quick notes:
- I'm not familiar with the process, but I wouldn't be surprised if my privileges might need to be restored after the transfer.
- The Travis-CI integration is currently hooked up to my Travis-CI account. We can keep using my Travis-CI account after the transfer, but maybe it would make more sense to use @nskinkel's Travis-CI account. I suspect that this setup might break during the transfer anyway.

**Comment by dwtj** [comment]
I just tried to transfer ownership, but I got an error from GitHub: "nskinkel already has a repository in the dwtj/tweetnaclrs network". I suspect that this just means that @nskinkel will need to delete their fork before the transfer can happen.

![screen shot 2015-09-13 at 12 05 48 pm](https://cloud.githubusercontent.com/assets/2457848/9837799/6923ee56-5a10-11e5-82e5-717089490384.png)

**Comment by nskinkel** [comment]
Yeah, it doesn't let you transfer ownership if someone has a fork.

Fork is deleted now so it should work.

**Comment by dwtj** [comment]
Transfer complete.
